name: Copilot Setup Steps

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    environment: copilot
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install MCP server dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Verify installation
        run: |
          python -c "import fastmcp, requests, psutil; print('All dependencies installed successfully')"
